### ISSUE TITLE
EPUB3 and ADE 4.0+

### ISSUE THREAD

**Issue by senthilmm** [dvschultz/99problems#55]
Known issues in ADE 4.0

Known issues with rendering EPUB 3 content:

On Windows, EPUB 3 features do not render if the IE version is less than 10.
On Windows, Detail, Bdi, Wbr tags are not supported.
On Windows, Mouse wheel scrolling is not supported.
Hitting Tab inside the contents of the book changes the content alignment.

As found on http://www.adobe.com/solutions/ebook/digital-editions/release-notes.html.

Strange to view epub3 in ADE, You need to upgrade IE?

**Comment by JayPanoz** [comment]
> Strange to view epub3 in ADE, You need to upgrade IE?

They indeed use an early version of Readium.js with Trident (IE’s rendering engine) and not Webkit as you would expect (because Readium).
